version: "2"
services:
  
  serviceA:
    image: "serbrech/service:latest"
    ports:
      - "60000"
    links:
      - consul1
    depends_on:
      - consul1
    environment:
      - SVC_NAME=serviceA
      - Env_ConsulHost=consul1
      - Env_ConsulPort=8500
  
  serviceB:
    image: "serbrech/service:latest"
    ports:
      - "60000"
    links:
      - consul2
    depends_on:
      - consul2
    environment:
      - SVC_NAME=serviceB
      - Env_ConsulHost=consul2
      - Env_ConsulPort=8500
  serviceB_2:
    image: "serbrech/service:latest"
    ports:
      - "60000"
    links:
      - consul3
    depends_on:
      - consul3
    environment:
      - SVC_NAME=serviceB
      - Env_ConsulHost=consul3
      - Env_ConsulPort=8500
  
  consul1:
    image: "progrium/consul:latest"
    container_name: "consul1"
    hostname: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-server -bootstrap-expect 3 -ui-dir /ui"
  consul2:
    image: "progrium/consul:latest"
    container_name: "consul2"
    hostname: "consul2"
    ports:
      - "8402:8400"
      - "8502:8500"
      - "8602:53"
    command: "-server -join consul1"
    depends_on:
      - consul1
  consul3:
    image: "progrium/consul:latest"
    container_name: "consul3"
    hostname: "consul3"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "-server -join consul1"
    depends_on:
      - consul1